### ISSUE TITLE
Timeout Error with Example code

### ISSUE THREAD

**Issue by OmegaWolfProjects** [pbertie/inkyphat-node#31]
When I run the following example code I get the below error:
I have no idea what is causing this can you possible help?

**Code:**

```
const inkyphat = require('inkyphat')();
async function main() {
  await inkyphat.init();
  inkyphat.setPixel(1, 5, inkyphat.RED);
  inkyphat.drawRect(50, 100, inkyphat.BLACK);
  await inkyphat.redraw();
  await inkyphat.destroy();
}
main();
```

**Output:**

Error: Timeout
    at Timeout._onTimeout (/home/pi/mqtt/node_modules/inkyphat/lib/inkyphat-utils.js:14:12)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
(node:2400) UnhandledPromiseRejectionWarning: Error: Timeout
    at Timeout._onTimeout (/home/pi/mqtt/node_modules/inkyphat/lib/inkyphat-utils.js:14:12)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2400) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2400) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by pbertie** [comment]
This is a timeout waiting for the Busy Pin to change state. One of the differences between boards v1 and v2 was the state this pin was in when ready. This is identified as pin 17 in the inkyphat-utils.js but I didn't have both versions of the board to test this against. The code is a port from the python library with a few added features.
It might be that a newer board has been released where this busy pin has changed.

**Comment by OmegaWolfProjects** [comment]
Hi pbertie,
Thank you very much for taking the time to reply to me.

I'm looking at your "inkyphat-utils.js" right now. I don't have an oscilloscope to probe the Pi pins...
