### ISSUE TITLE
Enanchements

### ISSUE THREAD

**Issue by france193** [pbertie/inkyphat-node#4]
Hi! I find this application very interesting and I need your help to enananche it! 

1) What type of changes are needed to use with other inky_phat colors (like YELLOW version)?
2) It is possible to write some text using this library?

**Comment by pbertie** [comment]
Hi,
The yellow version of Inkyphat replaces the red particles with yellow so although the code will say red it will in fact set that pixel to yellow when connected to that hardware. I plan on adding an alias to make this clearer.

It's doesn't currently support text but as it's just an array of data that would be possible with a bit of work. I also plan to add the option to load an image file in.

As you may see I've added a light red which is achieved by setting it red then partly clearing that pixel. This same affect can be done with black and I plan to find a way to introduce this to the code so there are many shades.

**Comment by france193** [comment]
I have some problem using your code printing in YELLOW because I get a mixture of black and yellow... If I use the library available in python I get a "real" yello...

Could you explain me what is the correct procedure to write a text?
- Create an image with the text inside and then display this image?
- Print raw data: print text encoded in some mode? in what function should i have to pass those data?

Thank you very much for your availability!

**Comment by pbertie** [comment]
For the Yellow colour I've just looked again at the change in the python code for yellow support and they have changed the lookup table for the red/yellow channel when outputting yellow. I've not got a Yellow screen so i'm not able to experiment with it to render the colour faster but it is possible to add a new lookup profile for pimoroni_yellow with their values.

As for the Text/Images, these are features I'd like to add but haven't added yet, feel free to take a look if you want to have a go at adding these and do a Pull Request. The Python version does images by having a colour pallet and saying the image needs to have the colours in the right indexes to render correctly. My plan was to allow any image and for each pixel work out what the closest available colour was and use that. This fits in better with my plan to allow multiple shades, the render would therefore improve in quality the longer you let it take.

**Comment by pbertie** [comment]
@france193 I've made the changes to all the pimoroni yellow lookup table and created v1.1.0 that includes this. I don't have a yellow version of the screen so would appreciate it if you could let me know if this worked. I Added a `example-yellow.js` too which uses this. When I run it on my Red screen the yellow comes out as black, I was expecting it to be some shade of red but that's not necessarily a bad sign.

**Comment by nkhil** [comment]
@pbertie Thanks for making this - looks promising! 

I want to second the request to add text. I'd like to be able to call an API (the weather API for instance) and display the weather on the screen along with maybe an icon. 

I'm fairly new to the world of programming so I won't be able to contribute, even though I'd love to.
